routes/web.php
<?php

use Hryha\RequestLogger\Http\Controllers\RequestLoggerController;
use Hryha\RequestLogger\Http\Middleware\SetLocale;
use Illuminate\Foundation\Application;

$middleware = array_merge(config('request-logger.middleware'), [SetLocale::class]);

if (app() instanceof Application) { //Laravel
    Route::prefix('request-logs')->name('request-logs.')->middleware($middleware)->group(function () {
        Route::get('/', [RequestLoggerController::class, 'index'])->name('index');
        Route::get('/{id}/download', [RequestLoggerController::class, 'download'])->name('download');
        Route::get('/{id}/show', [RequestLoggerController::class, 'download'])->name('show');
        Route::get('/clear-all-logs', [RequestLoggerController::class, 'clearAllLogs'])->name('clearAllLogs');
    });
} else { //Lumen
    Route::group(['as' => 'request-logs', 'prefix' => 'request-logs', 'middleware' => $middleware], function () {
        Route::get('/', ['as' => 'index', 'uses' => 'Hryha\RequestLogger\Http\Controllers\RequestLoggerController@index']);
        Route::get('/{id}/download', ['as' => 'download', 'uses' => 'Hryha\RequestLogger\Http\Controllers\RequestLoggerController@download']);
        Route::get('/{id}/show', ['as' => 'show', 'uses' => 'Hryha\RequestLogger\Http\Controllers\RequestLoggerController@show']);
        Route::get('/clear-all-logs', ['as' => 'clearAllLogs', 'uses' => 'Hryha\RequestLogger\Http\Controllers\RequestLoggerController@clearAllLogs']);
    });
}

resources/views/index.blade.php
@extends('request-logs::layouts.default')
@section('content')
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ trans('request-logger::logs.title') }}</h1>
    </div>
    <div>
        <div class="d-flex">
            <div class="me-auto">
                <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseFilters" role="button"
                   aria-expanded="false" aria-controls="collapseFilters">
                    {{ trans('request-logger::logs.filtering') }}
                </a>
                <a class="btn btn-secondary"
                   href="{{route('request-logs.index')}}">{{ trans('request-logger::logs.filtering_reset') }}</a>
            </div>
            <div>
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#clearAllLogsModal">
                    {{ trans('request-logger::logs.clear_all_logs') }}
                </button>
            </div>
        </div>
        <div class="mt-3">
            @include('request-logs::partials.filtering')
        </div>
    </div>

    @include('request-logs::partials.logs')
    @include('request-logs::modals.log-view-modal')
    @include('request-logs::modals.clear-all-logs-modal')
@endsection

resources/views/layouts/default.blade.php
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{{asset(mix('bootstrap.css', 'vendor/request-logger'))}}" rel="stylesheet">
    <link href="{{asset(mix('app.css', 'vendor/request-logger'))}}" rel="stylesheet">
    <link href="{{asset(mix('jsonTree.css', 'vendor/request-logger'))}}" rel="stylesheet">
    @stack('styles')
    <title>Request Logs</title>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <main role="main" class="col-md-12 ml-sm-auto col-lg-12 px-4">
            @yield('content')
        </main>
    </div>
</div>
<script src="{{asset(mix('app.js', 'vendor/request-logger'))}}"></script>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
@stack('scripts')
</body>
</html>

resources/views/modals/clear-all-logs-modal.blade.php
<div class="modal fade" id="clearAllLogsModal" tabindex="-1" aria-labelledby="clearAllLogsModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ trans('request-logger::modals.clear_all_logs.title') }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>{{ trans('request-logger::modals.clear_all_logs.message') }}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    {{ trans('request-logger::modals.clear_all_logs.dismiss') }}
                </button>
                <a href="{{route('request-logs.clearAllLogs')}}" class="btn btn-danger">
                    {{ trans('request-logger::modals.clear_all_logs.confirm') }}
                </a>
            </div>
        </div>
    </div>
</div>

resources/views/modals/log-view-modal.blade.php
<div class="modal fade" id="modalViewData" tabindex="-1" aria-labelledby="modalViewDataLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"
                    id="modalViewDataLabel">{{ trans('request-logger::modals.log_view.title') }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <button class="btn btn-outline-secondary"
                            id="expandLogTree">{{ trans('request-logger::modals.log_view.expand_all') }}</button>
                    <button class="btn btn-outline-secondary"
                            id="collapseLogTree">{{ trans('request-logger::modals.log_view.collapse_all') }}</button>
                </div>
                <div id="tree-wrapper"></div>
            </div>
        </div>
    </div>
</div>

resources/views/partials/filtering.blade.php
<div class="collapse" id="collapseFilters">
    <div class="card card-body">
        <form type="GET" action="{{route('request-logs.index')}}">
            <div class="form-group row pb-3">
                <label for="url"
                       class="col-sm-2 col-form-label">{{ trans('request-logger::logs.filtering_by_url_label') }}</label>
                <div class="col-sm-10">
                    <input type="text" name="url" class="form-control" id="url"
                           value="{{$request->input('url', '')}}">
                </div>
            </div>
            <div class="form-group row pb-3">
                <label for="exclude_urls" class="col-sm-2 col-form-label">
                    {{ trans('request-logger::logs.filtering_by_exclude_urls_label') }}
                </label>
                <div class="col-sm-10">
                    <div id="exclude-url-container">
                        @forelse($request->input('exclude_urls', []) as  $url)
                            <div class="exclude-url-input-group {{ !$loop->first ? 'pt-1' : '' }}">
                                <div class="d-flex justify-content-start gap-1">
                                    <input type="text" name="exclude_urls[]" class="form-control"
                                           id="exclude_urls"
                                           value="{{$url}}">
                                    @if($loop->first)
                                        <button type="button" class="btn btn-success add-exclude-url-field">
                                            <ion-icon name="add-circle-sharp"></ion-icon>
                                        </button>
                                    @else
                                        <button type="button" class="btn btn-danger delete-exclude-url-field">
                                            <ion-icon name="trash-sharp"></ion-icon>
                                        </button>
                                    @endif
                                </div>
                            </div>
                        @empty
                            <div class="exclude-url-input-group">
                                <div class="d-flex justify-content-start gap-1">
                                    <input type="text" name="exclude_urls[]" class="form-control" id="exclude_urls">
                                    <button type="button" class="btn btn-success add-exclude-url-field">
                                        <ion-icon name="add-circle-sharp"></ion-icon>
                                    </button>
                                </div>
                            </div>
                        @endforelse
                    </div>
                </div>
            </div>
            <div class="form-group row pb-3">
                <label for="url" class="col-sm-2 col-form-label">
                    {{ trans('request-logger::logs.filtering_by_method_label') }}
                </label>
                <div class="col-sm-10">
                    <div class="form-check form-check-inline">
                        <input name="methods[]" class="form-check-input" type="checkbox" id="GET" value="GET"
                               @if(in_array('GET', $request->input('methods', []))) checked @endif>
                        <label class="form-check-label" for="GET">GET</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input name="methods[]" class="form-check-input" type="checkbox" id="POST" value="POST"
                               @if(in_array('POST', $request->input('methods', []))) checked @endif>
                        <label class="form-check-label" for="POST">POST</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input name="methods[]" class="form-check-input" type="checkbox" id="PUT" value="PUT"
                               @if(in_array('PUT', $request->input('methods', []))) checked @endif>
                        <label class="form-check-label" for="PUT">PUT</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input name="methods[]" class="form-check-input" type="checkbox" id="DELETE"
                               value="DELETE"
                               @if(in_array('DELETE', $request->input('methods', []))) checked @endif>
                        <label class="form-check-label" for="DELETE">DELETE</label>
                    </div>
                </div>
            </div>
            <div class="form-group row pb-3">
                <label for="response_status_code"
                       class="col-sm-2 col-form-label">{{ trans('request-logger::logs.filtering_by_status_label') }}</label>
                <div class="col-sm-10">
                    <input type="number" name="response_status_code" class="form-control"
                           id="response_status_code"
                           value="{{$request->input('response_status_code', '')}}">
                </div>
            </div>
            <div class="form-group row pb-3">
                <label for="fingerprint"
                       class="col-sm-2 col-form-label">{{ trans('request-logger::logs.filtering_by_fingerprint_label') }}</label>
                <div class="col-sm-10">
                    <input type="text" name="fingerprint" class="form-control"
                           id="fingerprint"
                           value="{{$request->input('fingerprint', '')}}">
                </div>
            </div>
            <div class="form-group row pb-3">
                <label for="exclude_fingerprints"
                       class="col-sm-2 col-form-label">{{ trans('request-logger::logs.filtering_by_exclude_fingerprints_label') }}</label>
                <div class="col-sm-10">
                    <div id="exclude-fingerprint-container">
                        @forelse($request->input('exclude_fingerprints', []) as  $fingerprint)
                            @if(!empty(trim($fingerprint)))
                                <div class="exclude-fingerprint-input-group {{ !$loop->first ? 'pt-1' : '' }}">
                                    <div class="d-flex justify-content-start gap-1">
                                        <input type="text" name="exclude_fingerprints[]" class="form-control"
                                               id="exclude_fingerprints"
                                               value="{{$fingerprint}}">
                                        @if($loop->first)
                                            <button type="button"
                                                    class="btn btn-success add-exclude-fingerprint-field">
                                                <ion-icon name="add-circle-sharp"></ion-icon>
                                            </button>
                                        @else
                                            <button type="button"
                                                    class="btn btn-danger delete-exclude-fingerprint-field">
                                                <ion-icon name="trash-sharp"></ion-icon>
                                            </button>
                                        @endif
                                    </div>
                                </div>
                            @endif
                        @empty
                            <div class="exclude-fingerprint-input-group">
                                <div class="d-flex justify-content-start gap-1">
                                    <input type="text" name="exclude_fingerprints[]" class="form-control"
                                           id="exclude_fingerprints">
                                    <button type="button" class="btn btn-success add-exclude-fingerprint-field">
                                        <ion-icon name="add-circle-sharp"></ion-icon>
                                    </button>
                                </div>
                            </div>
                        @endforelse
                    </div>
                </div>
            </div>
            <div class="form-group row pb-3">
                <label for="date_from"
                       class="col-sm-2 col-form-label">{{ trans('request-logger::logs.filtering_by_date_from_label') }}</label>
                <div class="col-sm-10">
                    <input type="datetime-local" name="date_from" class="form-control" id="date_from"
                           value="{{$request->input('date_from', '')}}">
                </div>
            </div>
            <div class="form-group row pb-3">
                <label for="date_to"
                       class="col-sm-2 col-form-label">{{ trans('request-logger::logs.filtering_by_date_to_label') }}</label>
                <div class="col-sm-10">
                    <input type="datetime-local" name="date_to" class="form-control" id="date_to"
                           value="{{$request->input('date_to', '')}}">
                </div>
            </div>
            <div class="form-group row pb-3">
                <label for="order"
                       class="col-sm-2 col-form-label">{{ trans('request-logger::logs.ordering') }}</label>
                <div class="col-sm-10">
                    <select class="form-control" name="order" id="">
                        <option value="date|desc"
                                @if($request->get('order', 'date|desc') === 'date|desc') selected @endif>
                            {{ trans('request-logger::logs.ordering_by_date_desc_label') }}
                        </option>
                        <option value="date|asc" @if($request->get('order', '') === 'date|asc') selected @endif>
                            {{ trans('request-logger::logs.ordering_by_date_asc_label') }}
                        </option>
                        <option value="response_status_code|desc"
                                @if($request->get('order', '') === 'response_status_code|desc') selected @endif>
                            {{ trans('request-logger::logs.ordering_by_status_desc_label') }}
                        </option>
                        <option value="response_status_code|asc"
                                @if($request->get('order', '') === 'response_status_code|asc') selected @endif>
                            {{ trans('request-logger::logs.ordering_by_status_asc_label') }}
                        </option>
                        <option value="duration_ms|desc"
                                @if($request->get('order', '') === 'duration_ms|desc') selected @endif>
                            {{ trans('request-logger::logs.ordering_by_duration_desc_label') }}
                        </option>
                        <option value="duration_ms|asc"
                                @if($request->get('order', '') === 'duration_ms|asc') selected @endif>
                            {{ trans('request-logger::logs.ordering_by_duration_asc_label') }}
                        </option>
                        <option value="memory|desc"
                                @if($request->get('order', '') === 'memory|desc') selected @endif>
                            {{ trans('request-logger::logs.ordering_by_memory_desc_label') }}
                        </option>
                        <option value="memory|asc"
                                @if($request->get('order', '') === 'memory|asc') selected @endif>
                            {{ trans('request-logger::logs.ordering_by_memory_asc_label') }}
                        </option>
                        <option value="repeating|desc"
                                @if($request->get('order', '') === 'repeating|desc') selected @endif>
                            {{ trans('request-logger::logs.ordering_by_repeating_desc_label') }}
                        </option>
                        <option value="repeating|asc"
                                @if($request->get('order', '') === 'repeating|asc') selected @endif>
                            {{ trans('request-logger::logs.ordering_by_repeating_asc_label') }}
                        </option>
                    </select>
                </div>
            </div>
            <div class="form-group row pb-3">
                <label for="date_to" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <button type="submit"
                            class="btn btn-success">{{ trans('request-logger::logs.filtering_submit') }}</button>
                </div>
            </div>
        </form>
    </div>
</div>

resources/views/partials/logs.blade.php
<div class="card card-body mt-3">
    <h5 class="card-title">{{ trans('request-logger::logs.total_title', ['total' => $total]) }}</h5>
    <div class="table-responsive">
        <table id="request-logs" class="table table-sm">
            <thead>
            <tr>
                <th>{{ trans('request-logger::logs.url_column_title') }}</th>
                <th>{{ trans('request-logger::logs.status_column_title') }}</th>
                <th>{{ trans('request-logger::logs.duration_column_title') }}</th>
                <th>{{ trans('request-logger::logs.memory_column_title') }}</th>
                <th>{{ trans('request-logger::logs.ip_column_title') }}</th>
                <th>{{ trans('request-logger::logs.date_column_title') }}</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach($logs as $log)
                <tr>
                    <td class="column-url">
                        <div>
                            <b class="{{ $log->methodClass }}">{{ $log->method }}</b> {{ $log->url_decoded }}
                        </div>
                        <div>
                            <span class="badge bg-secondary rounded-circle">{{ $log->repeating }}</span>
                            {{ $log->fingerprint }}
                        </div>
                    </td>
                    <td class="column-status-code">
                        <span class="badge {{ $log->status_class }}">{{ $log->response_status_code }}</span>
                    </td>
                    <td class="column-duration">{{ $log->duration_ms }} ms</td>
                    <td class="column-memory">{{ $log->memory }} MB</td>
                    <td>{{ $log->ip }}</td>
                    <td>
                        <div>{{ $log->timeString }}</div>
                        <div>{{ $log->dateString }}</div>
                    </td>
                    <td>
                        <div class="d-flex justify-content-end">
                            <a class="btn btn-primary m-1" data-bs-toggle="modal" data-bs-target="#modalViewData"
                               data-id="{{ $log->id }}">
                                <ion-icon name="eye-sharp"></ion-icon>
                            </a>
                            <a class="btn btn-success m-1"
                               href="{{ route('request-logs.download', ['id' => $log->id]) }}">
                                <ion-icon name="download-sharp"></ion-icon>
                            </a>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
            @if ($logs->hasPages())
                <tfoot>
                <tr>
                    <td colspan="7">
                        {{ $logs->appends($request->except('page'))->links() }}
                    </td>
                </tr>
                </tfoot>
            @endif
        </table>
    </div>
</div>